package Method.Client;

import Method.Client.clickgui.ClickGui;
import Method.Client.managers.CommandManager;
import Method.Client.managers.FileManager;
import Method.Client.managers.SettingsManager;
import Method.Client.module.ModuleManager;
import Method.Client.module.Onscreen.OnscreenGUI;
import Method.Client.utils.CustomEventsHandler;
import Method.Client.utils.EventsHandler;
import Method.Client.utils.Creativetabs.CreativeTabArmor;
import Method.Client.utils.Creativetabs.CreativeTabBlocks;
import Method.Client.utils.Creativetabs.CreativeTabBreak;
import Method.Client.utils.Creativetabs.CreativeTabFun;
import Method.Client.utils.Creativetabs.CreativeTabItems;
import Method.Client.utils.Factory.MethodConfig;
import Method.Client.utils.Screens.NewScreen;
import Method.Client.utils.Screens.Custom.Esp.EspGui;
import Method.Client.utils.Screens.Custom.Packet.AntiPacketGui;
import Method.Client.utils.Screens.Custom.Search.SearchGui;
import Method.Client.utils.Screens.Custom.Xray.XrayGui;
import Method.Client.utils.font.CFont;
import Method.Client.utils.proxy.ClientProxy;
import Method.Client.utils.proxy.IProxy;
import Method.Client.utils.system.Nan0EventRegister;
import net.minecraft.client.Minecraft;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.Mod.Instance;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.lwjgl.opengl.Display;

@Mod(
   modid = "futurex",
   name = "FutureX",
   version = "0.0.1",
   acceptableRemoteVersions = "*",
   guiFactory = "Method.Client.utils.Factory.MethodGuiFactory"
)
public class Main {
   @SidedProxy(
      clientSide = "Method.Client.utils.proxy.ClientProxy",
      serverSide = "Method.Client.utils.proxy.ServerProxy"
   )
   public static IProxy proxy;
   public static final String MODID = "futurex";
   public static final String NAME = "FutureX";
   public static final String MODCREDITS = "FutureX";
   public static final String VERSION = "0.0.1";
   public static final String MCVERSION = "1.12.2";
   public static final String MODURL = "https://github.com/FutureXClient/FutureX";
   public static final String MODLOGO = "assets/futurex/futurex.png";
   public static final Logger LOGGER = LogManager.getLogger();
   @Instance
   public static Main instance;
   public static SettingsManager setmgr;
   public static EventsHandler Evtmgr;
   public static CustomEventsHandler Cevtmgr;
   public static OnscreenGUI OnscreenGUI;
   public static AntiPacketGui AntiPacketgui;
   public static XrayGui Xray;
   public static SearchGui Search;
   public static EspGui GuiEsp;
   public static ClickGui ClickGui;
   public static MethodConfig config;

   @EventHandler
   public void preInit(FMLPreInitializationEvent event) {
      LOGGER.info("Initializing FutureX Version 0.0.1");
      event.getModMetadata().autogenerated = false;
      event.getModMetadata().name = "FutureX";
      event.getModMetadata().authorList.clear();
      event.getModMetadata().credits = "FutureX";
      event.getModMetadata().url = "https://github.com/FutureXClient/FutureX";
      event.getModMetadata().logoFile = "assets/futurex/futurex.png";
      new CreativeTabBlocks();
      new CreativeTabItems();
      new CreativeTabBreak();
      new CreativeTabArmor();
      new CreativeTabFun();
      config = new MethodConfig();
      config.preInit(event);
      Minecraft.func_71410_x().field_71474_y.field_74335_Z = 2;
      CFont.setupfont();
      MinecraftForge.EVENT_BUS.register(this);
   }

   @EventHandler
   public void init(FMLInitializationEvent event) {
      LOGGER.info("Setup FutureX Version 0.0.1");
      proxy.init(event);
      Evtmgr = new EventsHandler();
      Cevtmgr = new CustomEventsHandler();
      Xray = new XrayGui();
      Search = new SearchGui();
      AntiPacketgui = new AntiPacketGui();
      GuiEsp = new EspGui();
      setmgr = new SettingsManager();
      new ModuleManager();
      new NewScreen();
      OnscreenGUI = new OnscreenGUI();
      ClickGui = new ClickGui();
   }

   @EventHandler
   public void postInit(FMLPostInitializationEvent event) {
      LOGGER.info("Final FutureX Version 0.0.1");
      new FileManager();
      Nan0EventRegister.register(MinecraftForge.EVENT_BUS, ClickGui);
      Nan0EventRegister.register(MinecraftForge.EVENT_BUS, OnscreenGUI);
      Nan0EventRegister.register(MinecraftForge.EVENT_BUS, Evtmgr);
      Nan0EventRegister.register(MinecraftForge.EVENT_BUS, Cevtmgr);
      Nan0EventRegister.register(MinecraftForge.EVENT_BUS, AntiPacketgui);
      Nan0EventRegister.register(MinecraftForge.EVENT_BUS, GuiEsp);
      Nan0EventRegister.register(MinecraftForge.EVENT_BUS, Xray);
      if (CommandManager.getInstance() == null) {
         CommandManager.getInstance();
      }

      Display.setTitle("FutureX");
      ClientProxy.Gl = ModuleManager.getModuleByName("ArmorRender");
   }
}
